version: "3.8"
services:
  db:
    image: postgres:16
    container_name: shelta-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: shelta_user
      POSTGRES_PASSWORD: shelta_password
      POSTGRES_DB: shelta_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
