export const metrics = [
  {
    label: "Total properties",
    value: "24",
    note: "312 units",
    change: "+2 this year",
    icon: "Building2",
    tone: "green",
  },
  {
    label: "Occupancy rate",
    value: "92.6%",
    note: "289 occupied",
    change: "+1.8%",
    icon: "Users",
    tone: "blue",
  },
  {
    label: "Rent collected",
    value: "$428,650",
    note: "of $482,100",
    change: "88.9%",
    icon: "TrendingUp",
    tone: "green",
  },
  {
    label: "Outstanding",
    value: "$53,450",
    note: "18 tenants",
    change: "+6.2%",
    icon: "CircleAlert",
    tone: "orange",
  },
];

export const bars = [64, 71, 68, 76, 74, 82, 79, 88, 84, 91, 89, 96];
export const monthLabels = [
  "Sep",
  "Oct",
  "Nov",
  "Dec",
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
];

export const activity = [
  {
    icon: "ArrowDownRight",
    tone: "green",
    title: "Rent payment received",
    meta: "Amara Okafor · Palm View, Unit 4B",
    time: "12 min",
    value: "+$2,400",
  },
  {
    icon: "Wrench",
    tone: "orange",
    title: "Maintenance request assigned",
    meta: "Water leak · Meridian Court, Unit 2A",
    time: "34 min",
    value: "High",
  },
  {
    icon: "Users",
    tone: "blue",
    title: "New tenant added",
    meta: "Daniel Brooks · Kingsley House, Unit 7",
    time: "1 hr",
    value: "Active",
  },
  {
    icon: "ArrowUpRight",
    tone: "red",
    title: "Contractor payment recorded",
    meta: "BrightFix Plumbing · INV-2048",
    time: "3 hrs",
    value: "-$860",
  },
];

export const tasks = [
  {
    date: "14",
    month: "AUG",
    title: "3 leases expire soon",
    detail: "Within the next 30 days",
    tone: "orange",
  },
  {
    date: "16",
    month: "AUG",
    title: "Routine inspection",
    detail: "Palm View Apartments",
    tone: "blue",
  },
  {
    date: "18",
    month: "AUG",
    title: "5 rent payments overdue",
    detail: "$12,840 outstanding",
    tone: "red",
  },
];

export const landlords = [
  {
    id: "LL-001",
    name: "Amina Bello",
    initials: "AB",
    email: "amina.bello@example.com",
    phone: "+234 803 114 5502",
    address: "18 Adeola Odeku Street, Victoria Island",
    properties: 4,
    units: 56,
    occupied: 51,
    monthlyRent: 92400,
    outstanding: 5700,
    attention: 3,
    portal: "Active",
  },
  {
    id: "LL-002",
    name: "Chinedu Okoro",
    initials: "CO",
    email: "chinedu.okoro@example.com",
    phone: "+234 806 228 1904",
    address: "7 Fola Osibo Road, Lekki",
    properties: 3,
    units: 42,
    occupied: 36,
    monthlyRent: 74100,
    outstanding: 2250,
    attention: 2,
    portal: "Active",
  },
  {
    id: "LL-003",
    name: "David Kingsley",
    initials: "DK",
    email: "david.kingsley@example.com",
    phone: "+234 701 889 2250",
    address: "5 Alexander Avenue, Ikoyi",
    properties: 2,
    units: 24,
    occupied: 24,
    monthlyRent: 53200,
    outstanding: 0,
    attention: 0,
    portal: "Active",
  },
  {
    id: "LL-004",
    name: "Nora Holdings",
    initials: "NH",
    email: "admin@nora-holdings.com",
    phone: "+234 809 445 7012",
    address: "11 Broad Street, Lagos Island",
    properties: 6,
    units: 98,
    occupied: 87,
    monthlyRent: 138600,
    outstanding: 18400,
    attention: 4,
    portal: "Invited",
  },
  {
    id: "LL-005",
    name: "Tunde Adeyemi",
    initials: "TA",
    email: "tunde.adeyemi@example.com",
    phone: "+234 705 812 3349",
    address: "23 Isaac John Street, Ikeja",
    properties: 3,
    units: 36,
    occupied: 31,
    monthlyRent: 58600,
    outstanding: 7100,
    attention: 1,
    portal: "Inactive",
  },
  {
    id: "LL-006",
    name: "Forge Estates",
    initials: "FE",
    email: "office@forge-estates.com",
    phone: "+234 811 205 6618",
    address: "6 Industrial Crescent, Yaba",
    properties: 6,
    units: 56,
    occupied: 52,
    monthlyRent: 65200,
    outstanding: 20000,
    attention: 2,
    portal: "Active",
  },
];

export const properties = [
  {
    id: "PR-001",
    name: "Palm View Apartments",
    address: "18 Marina Road, Victoria Island",
    landlord: "Amina Bello",
    type: "Apartment",
    units: 24,
    occupied: 22,
    rent: "$48,600",
    status: "Active",
    accent: "forest",
  },
  {
    id: "PR-002",
    name: "Meridian Court",
    address: "42 Admiralty Way, Lekki",
    landlord: "Chinedu Okoro",
    type: "Apartment",
    units: 18,
    occupied: 15,
    rent: "$36,200",
    status: "Active",
    accent: "gold",
  },
  {
    id: "PR-003",
    name: "Kingsley House",
    address: "7 Thompson Avenue, Ikoyi",
    landlord: "David Kingsley",
    type: "Residential",
    units: 12,
    occupied: 12,
    rent: "$31,800",
    status: "Active",
    accent: "brick",
  },
  {
    id: "PR-004",
    name: "Harbour Point Offices",
    address: "11 Broad Street, Lagos Island",
    landlord: "Nora Holdings",
    type: "Commercial",
    units: 32,
    occupied: 27,
    rent: "$72,400",
    status: "Active",
    accent: "blue",
  },
  {
    id: "PR-005",
    name: "Cedar Grove",
    address: "23 Isaac John Street, Ikeja",
    landlord: "Tunde Adeyemi",
    type: "Townhouse",
    units: 10,
    occupied: 7,
    rent: "$19,500",
    status: "Under Maintenance",
    accent: "olive",
  },
  {
    id: "PR-006",
    name: "The Foundry Lofts",
    address: "6 Industrial Crescent, Yaba",
    landlord: "Forge Estates",
    type: "Mixed Use",
    units: 16,
    occupied: 14,
    rent: "$28,900",
    status: "Active",
    accent: "slate",
  },
];

export const units = [
  {
    id: "UNT-001",
    number: "4B",
    property: "Palm View Apartments",
    landlord: "Amina Bello",
    floor: "4th Floor",
    type: "2 Bedroom",
    beds: 2,
    baths: 2,
    rent: 2400,
    deposit: 4800,
    status: "Occupied",
    tenant: "Amara Okafor",
    lease: "30 Nov 2026",
  },
  {
    id: "UNT-002",
    number: "2A",
    property: "Meridian Court",
    landlord: "Chinedu Okoro",
    floor: "2nd Floor",
    type: "1 Bedroom",
    beds: 1,
    baths: 1,
    rent: 1850,
    deposit: 3700,
    status: "Under Repair",
    tenant: null,
    lease: null,
  },
  {
    id: "UNT-003",
    number: "7",
    property: "Kingsley House",
    landlord: "David Kingsley",
    floor: "Ground Floor",
    type: "Studio",
    beds: 1,
    baths: 1,
    rent: 1450,
    deposit: 2900,
    status: "Occupied",
    tenant: "Daniel Brooks",
    lease: "18 Mar 2027",
  },
  {
    id: "UNT-004",
    number: "12C",
    property: "Harbour Point Offices",
    landlord: "Nora Holdings",
    floor: "12th Floor",
    type: "Office Suite",
    beds: 0,
    baths: 2,
    rent: 4200,
    deposit: 8400,
    status: "Vacant",
    tenant: null,
    lease: null,
  },
  {
    id: "UNT-005",
    number: "G2",
    property: "Cedar Grove",
    landlord: "Tunde Adeyemi",
    floor: "Ground Floor",
    type: "3 Bedroom",
    beds: 3,
    baths: 3,
    rent: 3100,
    deposit: 6200,
    status: "Reserved",
    tenant: "Pending application",
    lease: "Starts 01 Sep 2026",
  },
  {
    id: "UNT-006",
    number: "5A",
    property: "The Foundry Lofts",
    landlord: "Forge Estates",
    floor: "5th Floor",
    type: "Loft",
    beds: 2,
    baths: 2,
    rent: 2750,
    deposit: 5500,
    status: "Occupied",
    tenant: "Maya Ellis",
    lease: "09 Jan 2027",
  },
  {
    id: "UNT-007",
    number: "8B",
    property: "Palm View Apartments",
    landlord: "Amina Bello",
    floor: "8th Floor",
    type: "3 Bedroom",
    beds: 3,
    baths: 2,
    rent: 3400,
    deposit: 6800,
    status: "Vacant",
    tenant: null,
    lease: null,
  },
  {
    id: "UNT-008",
    number: "3D",
    property: "Meridian Court",
    landlord: "Chinedu Okoro",
    floor: "3rd Floor",
    type: "2 Bedroom",
    beds: 2,
    baths: 2,
    rent: 2250,
    deposit: 4500,
    status: "Occupied",
    tenant: "Ifeoma Nwosu",
    lease: "22 Jun 2027",
  },
];

export const tenants = [
  {
    id: "TNT-1042",
    name: "Amara Okafor",
    initials: "AO",
    landlord: "Amina Bello",
    phone: "+234 803 441 9082",
    email: "amara.okafor@example.com",
    occupation: "Product Designer",
    employer: "Kora Digital",
    property: "Palm View Apartments",
    unit: "4B",
    rent: 2400,
    balance: 0,
    leaseStart: "01 Dec 2025",
    leaseEnd: "30 Nov 2026",
    status: "Active",
    payment: "Paid",
    guarantor: "Chika Okafor",
  },
  {
    id: "TNT-1041",
    name: "Daniel Brooks",
    initials: "DB",
    landlord: "David Kingsley",
    phone: "+234 706 228 1139",
    email: "daniel.brooks@example.com",
    occupation: "Consultant",
    employer: "Brooks Advisory",
    property: "Kingsley House",
    unit: "7",
    rent: 1450,
    balance: 0,
    leaseStart: "19 Mar 2026",
    leaseEnd: "18 Mar 2027",
    status: "Active",
    payment: "Paid",
    guarantor: "Sarah Brooks",
  },
  {
    id: "TNT-1038",
    name: "Maya Ellis",
    initials: "ME",
    landlord: "Forge Estates",
    phone: "+234 809 375 6640",
    email: "maya.ellis@example.com",
    occupation: "Architect",
    employer: "Form Studio",
    property: "The Foundry Lofts",
    unit: "5A",
    rent: 2750,
    balance: 1200,
    leaseStart: "10 Jan 2026",
    leaseEnd: "09 Jan 2027",
    status: "Active",
    payment: "Partial",
    guarantor: "Jon Ellis",
  },
  {
    id: "TNT-1034",
    name: "Ifeoma Nwosu",
    initials: "IN",
    landlord: "Chinedu Okoro",
    phone: "+234 802 115 7742",
    email: "ifeoma.nwosu@example.com",
    occupation: "Legal Counsel",
    employer: "Obi & Partners",
    property: "Meridian Court",
    unit: "3D",
    rent: 2250,
    balance: 2250,
    leaseStart: "23 Jun 2026",
    leaseEnd: "22 Jun 2027",
    status: "Active",
    payment: "Overdue",
    guarantor: "Ada Nwosu",
  },
  {
    id: "TNT-1029",
    name: "Kwame Mensah",
    initials: "KM",
    landlord: "Nora Holdings",
    phone: "+234 705 902 3811",
    email: "kwame.mensah@example.com",
    occupation: "Finance Manager",
    employer: "Apex Capital",
    property: "Harbour Point Offices",
    unit: "9A",
    rent: 3800,
    balance: 0,
    leaseStart: "01 Sep 2025",
    leaseEnd: "31 Aug 2026",
    status: "Expiring",
    payment: "Paid",
    guarantor: "Akosua Mensah",
  },
  {
    id: "TNT-1023",
    name: "Fatima Bello",
    initials: "FB",
    landlord: "Amina Bello",
    phone: "+234 811 420 0675",
    email: "fatima.bello@example.com",
    occupation: "Medical Doctor",
    employer: "Lagoon Hospital",
    property: "Palm View Apartments",
    unit: "6C",
    rent: 2850,
    balance: 5700,
    leaseStart: "15 Aug 2025",
    leaseEnd: "14 Aug 2026",
    status: "Notice Given",
    payment: "Overdue",
    guarantor: "Yusuf Bello",
  },
];

export const employees = [
  {
    id: "EMP-001",
    name: "Nathan Adebayo",
    initials: "NA",
    email: "nathan@northhaven.com",
    phone: "+234 803 112 4300",
    department: "Management",
    role: "Super Admin",
    status: "Active",
    properties: ["All properties"],
    lastActive: "Now",
  },
  {
    id: "EMP-002",
    name: "Adaeze Obi",
    initials: "AO",
    email: "adaeze@northhaven.com",
    phone: "+234 806 227 1184",
    department: "Property Operations",
    role: "Property Manager",
    status: "Active",
    properties: ["Palm View Apartments", "Meridian Court"],
    lastActive: "8 min ago",
  },
  {
    id: "EMP-003",
    name: "Samuel Eze",
    initials: "SE",
    email: "samuel@northhaven.com",
    phone: "+234 701 448 6032",
    department: "Finance",
    role: "Accountant",
    status: "Active",
    properties: ["All properties"],
    lastActive: "34 min ago",
  },
  {
    id: "EMP-004",
    name: "Grace Mensah",
    initials: "GM",
    email: "grace@northhaven.com",
    phone: "+234 809 335 7890",
    department: "Maintenance",
    role: "Maintenance Officer",
    status: "Active",
    properties: ["Harbour Point Offices", "Cedar Grove", "The Foundry Lofts"],
    lastActive: "1 hr ago",
  },
  {
    id: "EMP-005",
    name: "Tomi Lawson",
    initials: "TL",
    email: "tomi@northhaven.com",
    phone: "+234 705 201 6634",
    department: "Customer Support",
    role: "Front Desk",
    status: "Invited",
    properties: ["All properties"],
    lastActive: "Invite pending",
  },
  {
    id: "EMP-006",
    name: "Kelechi Udo",
    initials: "KU",
    email: "kelechi@northhaven.com",
    phone: "+234 811 702 1198",
    department: "Property Operations",
    role: "Property Manager",
    status: "Suspended",
    properties: ["Kingsley House"],
    lastActive: "2 days ago",
  },
];

export const rolePermissions = {
  "Super Admin": {
    Properties: ["View", "Create", "Edit", "Delete"],
    Tenants: ["View", "Create", "Edit", "Delete"],
    Transactions: ["View", "Create", "Edit", "Delete"],
    Reports: ["View", "Export"],
    Documents: ["View", "Upload", "Send", "Delete"],
    Maintenance: ["View", "Create", "Assign", "Edit"],
    Employees: ["View", "Manage"],
  },
  "Property Manager": {
    Properties: ["View", "Edit"],
    Tenants: ["View", "Create", "Edit"],
    Transactions: ["View", "Create"],
    Reports: ["View"],
    Documents: ["View", "Upload", "Send"],
    Maintenance: ["View", "Create", "Assign", "Edit"],
    Employees: ["View"],
  },
  Accountant: {
    Properties: ["View"],
    Tenants: ["View"],
    Transactions: ["View", "Create", "Edit"],
    Reports: ["View", "Export"],
    Documents: ["View", "Upload"],
    Maintenance: ["View"],
    Employees: [],
  },
  "Maintenance Officer": {
    Properties: ["View"],
    Tenants: ["View"],
    Transactions: [],
    Reports: [],
    Documents: ["View", "Upload"],
    Maintenance: ["View", "Create", "Edit"],
    Employees: [],
  },
  "Front Desk": {
    Properties: ["View"],
    Tenants: ["View", "Create", "Edit"],
    Transactions: ["View"],
    Reports: [],
    Documents: ["View", "Upload", "Send"],
    Maintenance: ["View", "Create"],
    Employees: [],
  },
};

export const leases = [
  {
    id: "LSE-2041",
    tenant: "Amara Okafor",
    landlord: "Amina Bello",
    property: "Palm View Apartments",
    unit: "4B",
    start: "01 Dec 2025",
    end: "30 Nov 2026",
    rent: 2400,
    schedule: "Monthly",
    status: "Active",
    document: "Signed lease agreement.pdf",
    signed: true,
  },
  {
    id: "LSE-2038",
    tenant: "Daniel Brooks",
    landlord: "David Kingsley",
    property: "Kingsley House",
    unit: "7",
    start: "19 Mar 2026",
    end: "18 Mar 2027",
    rent: 1450,
    schedule: "Monthly",
    status: "Active",
    document: "Tenancy agreement.pdf",
    signed: true,
  },
  {
    id: "LSE-2034",
    tenant: "Maya Ellis",
    landlord: "Forge Estates",
    property: "The Foundry Lofts",
    unit: "5A",
    start: "10 Jan 2026",
    end: "09 Jan 2027",
    rent: 2750,
    schedule: "Monthly",
    status: "Active",
    document: "Lease - Maya Ellis.pdf",
    signed: true,
  },
  {
    id: "LSE-2029",
    tenant: "Ifeoma Nwosu",
    landlord: "Chinedu Okoro",
    property: "Meridian Court",
    unit: "3D",
    start: "23 Jun 2026",
    end: "22 Jun 2027",
    rent: 2250,
    schedule: "Quarterly",
    status: "Active",
    document: "Lease agreement.pdf",
    signed: true,
  },
  {
    id: "LSE-2024",
    tenant: "Kwame Mensah",
    landlord: "Nora Holdings",
    property: "Harbour Point Offices",
    unit: "9A",
    start: "01 Sep 2025",
    end: "31 Aug 2026",
    rent: 3800,
    schedule: "Quarterly",
    status: "Expiring",
    document: "Commercial lease.pdf",
    signed: true,
  },
  {
    id: "LSE-2018",
    tenant: "Fatima Bello",
    landlord: "Amina Bello",
    property: "Palm View Apartments",
    unit: "6C",
    start: "15 Aug 2025",
    end: "14 Aug 2026",
    rent: 2850,
    schedule: "Monthly",
    status: "Termination",
    document: "Signed tenancy agreement.pdf",
    signed: true,
  },
];

export const documents = [
  {
    id: "DOC-401",
    name: "Signed lease agreement.pdf",
    category: "Lease",
    owner: "Amara Okafor",
    landlord: "Amina Bello",
    property: "Palm View Apartments",
    version: 3,
    updated: "08 Aug 2026",
    access: "Tenant & landlord",
    status: "Signed",
  },
  {
    id: "DOC-398",
    name: "Move-in inspection.pdf",
    category: "Inspection",
    owner: "Daniel Brooks",
    landlord: "David Kingsley",
    property: "Kingsley House",
    version: 1,
    updated: "02 Aug 2026",
    access: "Tenant & landlord",
    status: "Final",
  },
  {
    id: "DOC-392",
    name: "Deed of assignment.pdf",
    category: "Ownership",
    owner: "Nora Holdings",
    landlord: "Nora Holdings",
    property: "Harbour Point Offices",
    version: 2,
    updated: "28 Jul 2026",
    access: "Agency & landlord",
    status: "Verified",
  },
  {
    id: "DOC-387",
    name: "Plumbing invoice 2048.pdf",
    category: "Maintenance",
    owner: "BrightFix Plumbing",
    landlord: "Chinedu Okoro",
    property: "Meridian Court",
    version: 1,
    updated: "26 Jul 2026",
    access: "Agency & landlord",
    status: "Final",
  },
  {
    id: "DOC-380",
    name: "Guarantor identification.pdf",
    category: "Tenant",
    owner: "Maya Ellis",
    landlord: "Forge Estates",
    property: "The Foundry Lofts",
    version: 1,
    updated: "19 Jul 2026",
    access: "Agency only",
    status: "Verified",
  },
];

export const transactions = [
  {
    id: "TXN-8201",
    type: "Income",
    category: "Rent payment",
    amount: 2400,
    date: "11 Aug 2026",
    property: "Palm View Apartments",
    unit: "4B",
    landlord: "Amina Bello",
    tenant: "Amara Okafor",
    reference: "RNT-AUG-1042",
    method: "Bank transfer",
    receipt: "RCPT-8201",
    notes: "August rent paid in full",
    status: "Completed",
  },
  {
    id: "TXN-8200",
    type: "Expense",
    category: "Repairs",
    amount: 860,
    date: "11 Aug 2026",
    property: "Meridian Court",
    unit: "2A",
    landlord: "Chinedu Okoro",
    tenant: null,
    reference: "INV-2048",
    method: "Bank transfer",
    receipt: "BrightFix invoice.pdf",
    notes: "Emergency plumbing repair",
    status: "Completed",
  },
  {
    id: "TXN-8198",
    type: "Income",
    category: "Rent payment",
    amount: 1550,
    date: "10 Aug 2026",
    property: "The Foundry Lofts",
    unit: "5A",
    landlord: "Forge Estates",
    tenant: "Maya Ellis",
    reference: "RNT-AUG-1038",
    method: "Card",
    receipt: "RCPT-8198",
    notes: "Partial August payment",
    status: "Partial",
  },
  {
    id: "TXN-8195",
    type: "Income",
    category: "Rent payment",
    amount: 1450,
    date: "09 Aug 2026",
    property: "Kingsley House",
    unit: "7",
    landlord: "David Kingsley",
    tenant: "Daniel Brooks",
    reference: "RNT-AUG-1041",
    method: "Bank transfer",
    receipt: "RCPT-8195",
    notes: "August rent",
    status: "Completed",
  },
  {
    id: "TXN-8192",
    type: "Expense",
    category: "Cleaning",
    amount: 420,
    date: "08 Aug 2026",
    property: "Harbour Point Offices",
    unit: "Common areas",
    landlord: "Nora Holdings",
    tenant: null,
    reference: "CLN-882",
    method: "Cash",
    receipt: "Cleaning receipt.jpg",
    notes: "Monthly common area cleaning",
    status: "Completed",
  },
  {
    id: "TXN-8189",
    type: "Income",
    category: "Security deposit",
    amount: 6200,
    date: "07 Aug 2026",
    property: "Cedar Grove",
    unit: "G2",
    landlord: "Tunde Adeyemi",
    tenant: "Pending application",
    reference: "DEP-G2-2026",
    method: "Bank transfer",
    receipt: "RCPT-8189",
    notes: "Reservation security deposit",
    status: "Completed",
  },
  {
    id: "TXN-8185",
    type: "Expense",
    category: "Utilities",
    amount: 1280,
    date: "05 Aug 2026",
    property: "Palm View Apartments",
    unit: "Common areas",
    landlord: "Amina Bello",
    tenant: null,
    reference: "EKEDC-JUL-882",
    method: "Direct debit",
    receipt: "Utility bill.pdf",
    notes: "July common-area electricity",
    status: "Completed",
  },
];

export const rentSchedule = [
  {
    id: "RNT-1042",
    tenant: "Amara Okafor",
    landlord: "Amina Bello",
    property: "Palm View Apartments",
    unit: "4B",
    due: 2400,
    paid: 2400,
    dueDate: "01 Aug 2026",
    frequency: "Monthly",
    status: "Paid",
  },
  {
    id: "RNT-1041",
    tenant: "Daniel Brooks",
    landlord: "David Kingsley",
    property: "Kingsley House",
    unit: "7",
    due: 1450,
    paid: 1450,
    dueDate: "01 Aug 2026",
    frequency: "Monthly",
    status: "Paid",
  },
  {
    id: "RNT-1038",
    tenant: "Maya Ellis",
    landlord: "Forge Estates",
    property: "The Foundry Lofts",
    unit: "5A",
    due: 2750,
    paid: 1550,
    dueDate: "01 Aug 2026",
    frequency: "Monthly",
    status: "Partial",
  },
  {
    id: "RNT-1034",
    tenant: "Ifeoma Nwosu",
    landlord: "Chinedu Okoro",
    property: "Meridian Court",
    unit: "3D",
    due: 2250,
    paid: 0,
    dueDate: "01 Aug 2026",
    frequency: "Monthly",
    status: "Overdue",
  },
  {
    id: "RNT-1029",
    tenant: "Kwame Mensah",
    landlord: "Nora Holdings",
    property: "Harbour Point Offices",
    unit: "9A",
    due: 11400,
    paid: 11400,
    dueDate: "01 Jul 2026",
    frequency: "Quarterly",
    status: "Paid",
  },
  {
    id: "RNT-1023",
    tenant: "Fatima Bello",
    landlord: "Amina Bello",
    property: "Palm View Apartments",
    unit: "6C",
    due: 2850,
    paid: 0,
    dueDate: "01 Aug 2026",
    frequency: "Monthly",
    status: "Overdue",
  },
];

export const maintenanceRequests = [
  {
    id: "MNT-301",
    title: "Water leak under kitchen sink",
    category: "Plumbing",
    description:
      "Continuous leak from the pipe joint under the kitchen sink. Cabinet base is getting wet.",
    landlord: "Chinedu Okoro",
    property: "Meridian Court",
    unit: "2A",
    tenant: "Ifeoma Nwosu",
    priority: "High",
    status: "Assigned",
    assignee: "Grace Mensah",
    created: "11 Aug 2026",
    updated: "11 Aug 2026",
    estimatedCost: 860,
    invoice: "INV-2048",
    photos: 3,
  },
  {
    id: "MNT-299",
    title: "Air conditioning not cooling",
    category: "HVAC",
    description: "Living room AC powers on but does not cool below room temperature.",
    landlord: "Amina Bello",
    property: "Palm View Apartments",
    unit: "6C",
    tenant: "Fatima Bello",
    priority: "Medium",
    status: "In Progress",
    assignee: "CoolAir Services",
    created: "10 Aug 2026",
    updated: "11 Aug 2026",
    estimatedCost: 520,
    invoice: null,
    photos: 1,
  },
  {
    id: "MNT-295",
    title: "Lobby lighting replacement",
    category: "Electrical",
    description: "Four ceiling fixtures in the east lobby require replacement.",
    landlord: "Nora Holdings",
    property: "Harbour Point Offices",
    unit: "Common areas",
    tenant: null,
    priority: "Low",
    status: "Open",
    assignee: null,
    created: "09 Aug 2026",
    updated: "09 Aug 2026",
    estimatedCost: 340,
    invoice: null,
    photos: 2,
  },
  {
    id: "MNT-291",
    title: "Bedroom window lock damaged",
    category: "Security",
    description: "Window lock no longer closes securely and should be replaced.",
    landlord: "Forge Estates",
    property: "The Foundry Lofts",
    unit: "5A",
    tenant: "Maya Ellis",
    priority: "High",
    status: "Completed",
    assignee: "Grace Mensah",
    created: "05 Aug 2026",
    updated: "10 Aug 2026",
    estimatedCost: 180,
    invoice: "INV-1994",
    photos: 2,
  },
  {
    id: "MNT-287",
    title: "Routine generator service",
    category: "Equipment",
    description: "Quarterly generator service and filter replacement.",
    landlord: "Tunde Adeyemi",
    property: "Cedar Grove",
    unit: "Common areas",
    tenant: null,
    priority: "Medium",
    status: "Verified",
    assignee: "PowerPro Engineering",
    created: "01 Aug 2026",
    updated: "08 Aug 2026",
    estimatedCost: 750,
    invoice: "INV-1978",
    photos: 4,
  },
  {
    id: "MNT-282",
    title: "Bathroom extractor fan noise",
    category: "Electrical",
    description: "Extractor fan makes a loud grinding sound during operation.",
    landlord: "David Kingsley",
    property: "Kingsley House",
    unit: "7",
    tenant: "Daniel Brooks",
    priority: "Low",
    status: "Assigned",
    assignee: "Grace Mensah",
    created: "29 Jul 2026",
    updated: "07 Aug 2026",
    estimatedCost: 140,
    invoice: null,
    photos: 1,
  },
];
